apiVersion: aws.platformref.upbound.io/v1alpha1
kind: Cluster
metadata:
  name: platform-ref-aws
  namespace: default
  annotations:
    uptest.upbound.io/post-assert-hook: testhooks/delete-release.sh
spec:
  id: platform-ref-aws
  parameters:
    region: us-west-2
    nodes:
      count: 0
      size: small
    awsAuth:
      mapRoles: |
        - groups:
          - system:masters
          rolearn: arn:aws:iam::651643910964:role/AWSReservedSSO_AdministratorAccess_d91ffa8520c0883b
          username: cluster-admin
    services:
      kms:
        sopsSecretsOperatorKeyRoles:
          admin: '"arn:aws:iam::651643910964:user/crossplane-poc-service", "arn:aws:iam::651643910964:role/aws-reserved/sso.amazonaws.com/AWSReservedSSO_AdministratorAccess_d91ffa8520c0883b"'
    #   operators:
    #     sops:
    #       version: "34.5.1"
  writeConnectionSecretToRef:
    name: platform-ref-aws-kubeconfig
